### ISSUE TITLE
setPosition() hangs the controller

### ISSUE THREAD

**Issue by vmatos** [darwinop/webots-cross-compilation#1]
Calling setPosition of the servos in a fast sequence, hangs the controller.
e.g.:

for(i=0;i<NSERVOS;i++) {
  servos[i]->setPosition(0);
}

**Comment by darwinop** [comment]
Vitor
Did you run the full version of Sample.cpp?

**Comment by fabienrohrer** [comment]
A common Webots feedback loop should be like this:

``` c++
while(true){
  for(i=0; i<NSERVOS; i++)
    servos[i]->setPosition(0); // actuate
  step(8); // wait
}
```

This is strange because the code used to set the servo position is not supposed to have time delay:

``` c++
void Servo::setPosition(double position) {
  CM730 *cm730 = getRobot()->getCM730();
  int value = MX28::Angle2Value(position*180.0/M_PI);
  if(value >= 0 && value <= MX28::MAX_VALUE) {
    int error;
    cm730->WriteWord(mNamesToIDs[getName()], MX28::P_GOAL_POSITION_L, value, &error);
  }
}
```

@Chase, do you think that the WriteWord is problematic? (does it take time?)

**Comment by darwinop** [comment]
@Fabien

I am also puzzled about this delay issue. There's nothing wrong with WriteWord. About the time delay this is a Dynamixel-related issue.

Could you please upload the same inquiry here?
http://www.robotis.com/xe/qna_en
A Dynamixel expert from our company should be able to answer. I will keep a close watch. There is some delay time as shown in  this table for the MX-28, but the settings for Darwin is set to 0.
http://support.robotis.com/en/product/dynamixel/mx_series/mx-28.htm

This is weird.

**Comment by vmatos** [comment]
@chase 
I used the controller in my "check_angle_ctrl" branch. Where I removed all the managers, ball detection function and all that.

I haven't tested extensibly the problem, it was just a random hang that I get everytime I don't separate setPositions with delays.

I did not remove the managers and timer initializations in the Robo.cpp. Maybe some the Writeword gets interrupted by other kind of communication with CM730?

I accept suggestions on how to further test the issue.

I think that first I'll write a controller that executes the same steps of the algorithm in the Darwin's SDK, to see if the problem arises.

**Comment by vmatos** [comment]
I've created a short example to try to emulate the Webots wrappers for setPosition.

The robot executes as expected, and does not hang.

Fabien, it looks like something may be wrong on the wrappers. Should we add the device maps to this test?
Any other suggestion?

**Comment by chase** [comment]
Please use @darwinop instead of @chase. I've gotten four unnecessary notifications and would prefer not to have further ones.

Thank you :-)

**Comment by darwinop** [comment]
guys.
sorry for the non-response. i was supposed to be notified every time this board gets updated. however, the notification emails ended up under spam therefore i've been unaware of such updates.
if you would like to publish anything publicly please sign up with www.robotsource.org  and make your post there.

**Comment by fabienrohrer** [comment]
@vmatos Your example is very useful. It shows that WriteWord is done without a significative amount of time. And show the minimal statements required to run the real DARwIn-OP.

In my point of view here is the next step to debug.
- I commited a sample written in Webots style in this branch:
  https://github.com/fabienrohrer/webots-cross-compilation/tree/simple_set_position
- The only dependencies of this controller are resources/.../transfer/.../Robot.[ch]pp and resources/.../transfer/.../Servo.[ch]pp files. These files (Robot.[ch]pp and Servo.[ch]pp) have to be debugged in order to work exactly as your sample (test_set_position branch) 
- This controller is similar to the controller of your branch

Here is globally the order in which the Robot.hpp and Servo.hpp functions are called:
1. The Robot super class is instantiated first and has to initialize CM730, and other DARwIn-OP stuff.
-> the constuctor of the Robot class is maybe buggy!
2. The Servo::setPosition function is called.

The Robot::getTime function is also crutial.

=> I expect that the Robot::initDarwinOP function is maybe buggy.
=> I expect that the Robot::getTime function is maybe buggy.
=> If I look at your code, is change_current_dir() necessary? And what about the signal() statements? Maybe this has to be added into the Robot::initDarwinOP function.

Do you understand how to go on, Vitor?

**Comment by vmatos** [comment]
I think that the last merge solves this issue :)
Tomorrow I'll test it further and close this ticket.

@fabienrohrer I totally missed the change_current_dir(), I believe that was the problem.
signal() statements specify the handle function when those four termination/abort/console ctrl+c etc signals are arise. 
I don't know if any of those four signals are arise by Darwin's framework. For now I decided to ignore that signal handler.
