### ISSUE TITLE
mTimeStep of 16

### ISSUE THREAD

**Issue by darwinop** [darwinop/webots-cross-compilation#149]
Not exactly an issue but more of a curiosity.

WHy was the step increased from 8ms to 16ms? Is this related to the inconsistent pace in gait?

**Comment by fabienrohrer** [comment]
It is an optimisation trick for the remote-control mode. Indeed, when controlling the robot in remote-control, the physics of Webots is running (but the physics is very minimalistic because the robot doesn't move and enters in a sleep mode), and this imply that the remote-control slows down.
At 8 ms, the remote-control reaches 90% of the real-time.
At 16 ms, the remote-control reaches almost 100% of the real-time (which is much better)
