### ISSUE TITLE
include files

### ISSUE THREAD

**Issue by darwinop** [darwinop/webots-cross-compilation#217]
normally this goes like (sorry, i had to remove the '<' and '>' signs due to displaying issues)
# include managers/DARwInOPGaitManager.hpp

this new source has it as
# include DARwInOPGaitManager.hpp

Will this change be reflected when 7.1.1 gets released?

**Comment by fabienrohrer** [comment]
Hi Chase,

The second formalism is currently used in the controllers.
In fact this simply depends on how the Makefile includes the include directories. Please check the "-I" in:
https://github.com/darwinop/webots-cross-compilation/blob/master/projects/robots/darwin-op/controllers/soccer/Makefile

Sincerely,
Fabien Rohrer

**Comment by darwinop** [comment]
Hi Fabien
I noticed the change. This will obviously affect cross-compilation and simulation when compiling the controller (as of today). SO I wonder if future versions of Webots will follow the new formalism.

**Comment by DavidMansolino** [comment]
Dear Chase,

Yes the new versions of Webots will work this way, this has been changed when the manager library has been changed from static library to dynamic library.

Sincerely,
David

**Comment by darwinop** [comment]
Awesome
Thanks

**Comment by omichel** [comment]
Just a quick note to tell you that there was a distribution bug in Webots 7.1.2 for Window and Linux 32 which we released yesterday. The bug was affecting the darwin-op controllers which were crashing. I just fixed it and uploaded a patched Webots 7.1.2 for Window and Linux 32. So, if you downloaded 7.1.2 yesterday, please get it again now, uninstall the one from yesterday and install the new one instead.

Sorry for the trouble.

-Olivier
