### ISSUE TITLE
SYNC_WRITE within webots wrappers

### ISSUE THREAD

**Issue by vmatos** [darwinop/webots-cross-compilation#8]
Hello, 
It is my intention of discussing this matter openly, so that someone who might have an idea can join us.

Each write and read to the servos seems to suffer some kind of 1ms overhead, from my experience.
So, if one chooses to setPosition() all the servos inside a 'for' cycle, it will take 20 individual WRITE  position commands, 1 for each servo. This kind of 'for' cycle will take around 30 ms.

On the other hand, if we create a sync write command, the write commands for the servos will be serialized, and there will be no overhead.
I've tested this, and it seems that it doesn't even take 1ms. Which I find it strange, maybe I'm not timing correctly the sync write. 

I'll write about these timing issues in robotsource.org

@fabienrohrer ,
How could we create a SYNC_WRITE command within the webots wrappers?
We need to fill in a packet with all the joint positions, and then send the packet.
Pseudo code follows (example code is in my sync_write branch):

```
for(i=1:all servos) {
  packet[n++] = id
  packet[n++] = value low byte
  packet[n++] = value high byte
}
send packet
```

Therefore Servo::setPosition() would not send a write command with the joint value, maybe could only update a position table?
What would then trigger the sync write?

How could this be integrated in the Webots API without introducing changes to the API itself?

**Comment by omichel** [comment]
Hi,

Fabien is not working any more at Cyberbotics. I'll try to help you instead of him.

Webots automatically store all the joint positions provided with Servo::setPosition() and send them to Webots only when a Robot::step() is performed. So, there shouldn't be any problem with SYNC_WRITE, as it is already the default in Webots.

Does it answer your question properly?

-Olivier

**Comment by vmatos** [comment]
Then we could mimic Webots original behaviour in the wrappers?
If we call setPosition to a servo, in the next Robot:step() the updated joint values could be sent easily through SYNC_WRITE.

I was just thinking, if one wishes only to change a couple of servos, and leave the other joints unchanged, how can we agilize the implementation?
Or even If I have a program that I set joint1.setForce(0), while joint2.setPosition(joint2.getPosition()). What should happen if I call joint1.setPosition()?

Do we have access to these inner workings of Webots? It would be much easier to replicate the API.

Currently I'm waiting for some insight in the timings when reading from the servos from RobotSource.org

**Comment by omichel** [comment]
Sure, we could really mimic the original behavior of Webots in the wrappers as you propose.
There is no problem if one wishes to only change a couple of servos and leave the other unchanged, Webots will send a change notification only to the servos for which a new target value was provided. I believe we could do the same in the wrapper.

> Or even If I have a program that I set joint1.setForce(0), while joint2.setPosition(joint2.getPosition()). What should happen if I call joint1.setPosition()?

On the next call to Robot::step(), the libController will send the following information to Webots: set the force of joint1 to 0 and set the target position of joint1 to the value specified. It shouldn't send anything with respect to joint2 as it should detect that its target position value didn't change.

I would be happy to provide you with access to the inner workings of Webots. The easiest for you is probably that I answer your questions as I know the system very well. Otherwise, I can send you some source code of the libController library if you wish, but that will be quite difficult to understand...

**Comment by vmatos** [comment]
Well, my first questions would be:
1 - What kind of structure/mechanism is used to store the desired joint positions for the servos in Webots?
2 - At the time of updating the joint positions in step(), what is the mechanism to deciding which joints should be updated?

On another note, I am thinking of making a whole table read of the robot, regarding accelerometers and gyro values. Because at the moment, getValues() in gyro and acc class are each one triggering an independent word read. This creates unecessary USB overhead per word read.
I will try to make a one time table read in step(). Question:
Where can I store the values from Robot::step(), to be then returned through Gyro::getValues() ?

**Comment by omichel** [comment]
Hi,

> 1 - What kind of structure/mechanism is used to store the desired joint positions for the servos in Webots?

When the user calls Servo::setPosition(position), the position value is store inside the Servo object, but not yet sent to Webots. It is sent only when the Robot::step() function is called.

> 2 - At the time of updating the joint positions in step(), what is the mechanism to deciding which joints should be updated?

In Robot::step(), each Servo is parsed to check if a new position was provided with Servo::setPosition since the previous Robot::step() call. If not, nothing is sent to Webots, otherwise the new position is sent to Webots and immediately applied to the servo node.

It is good indeed to minimize the USB overhead by getting all the accelerometer and gyro values in a single shot (and storing these values in their respective objects as explained below).

To store the sensor values, I would suggest you to store them inside the device objects, i.e., simply by adding a field named "double values[3]" in the Gyro class (i.e., in Gyro.hpp and Gyro.cpp). Hence the Gyro::getValues() function would be simply implemented as { return values; }. You can apply the same system for other devices as well.

Does it sound right for you?

**Comment by vmatos** [comment]
It does sound right.
So, in Robot::step() should we access the servos, gyro and accelerometer through the mDevices attribute of Robot?

In Servo:: we can create a double mPosition to keep the desired servo position, private or public?. Should we have to create a public method for reading this desired value? We can't name it Servo::getPosition() because that returns the real servo position.
Do you have an example of the parsing function to check if a new position is provided for the Servo?

For Gyro and Acc, should double values[3] be private or public? Should we cretate a public method for changing the values[3] in the device from Robot::step()?
Then we would have these methods for changing the read values from the robot, available to the user  that programs the robot? Wouldn't it be undesirable?

**Comment by omichel** [comment]
> So, in Robot::step() should we access the servos, gyro and accelerometer through the mDevices attribute of Robot?

Yes, definitely. However, you should use standard getter and setter methods.

> In Servo:: we can create a double mPosition to keep the desired servo position, private or public?

Yes. It should be a private member, accessible through a getter and a setter method.

> Should we have to create a public method for reading this desired value? We can't name it Servo::getPosition() because that returns the real servo position.

Sure. Instead I would suggest to have a field named "mTargetPosition" and a method named double getTargetPosition(), as well as setTargetPosition(double position);

> Do you have an example of the parsing function to check if a new position is provided for the Servo?

The example I have is way to much complicated and will confuse you rather than help you. Simply adding a boolean field in Servo named for example "mTargetPositionChanged" should do the job if you see what I mean. Again, you will need to implement the corresponding getter and setter so that the Robot class can access this field.

> For Gyro and Acc, should double values[3] be private or public? Should we cretate a public method for changing the values[3] in the device from Robot::step()?

I believe it is better if they are private and you will have to implement a getter and setter methods (again).

> Then we would have these methods for changing the read values from the robot, available to the user that programs the robot? Wouldn't it be undesirable?

I understand your point... One option would be to make the Robot class a "friend class" of Servo, Gyro, Accelerometer, etc. and to make all the setter and some getter function private, so that the Robot class can access these private methods whereas the end user classes couldn't. Would that fix the problem you mentioned?

**Comment by vmatos** [comment]
That was the kind of solution I was looking for! I'll have to dust off my C++ concepts...
In a few days I'll try to implement this solution.

Thanks

**Comment by omichel** [comment]
All right. Let me know if any issue arises while implementing this.

Cheers,

**Comment by vmatos** [comment]
Ok, I''ve implemented SYNC WRITE for the servos and table read for Accelerometers and Gyro.
These implementations are in my branches, robot_sync_write and robot_table_read.
I think it works fairly well.

I think these should be revised before integration with the main branch.

@darwinop what do you think?

@darwinop, I have another question, what is the fastest method for reading the position of all joints? I post at robotsource, but I obtain no answers.

**Comment by DavidMansolino** [comment]
I think this issue can be closed since  SYNC WRITE is now used for updating the servos and BULKREAD is used to read the servos states and sensors values.
